### ISSUE TITLE
Missing features of linker script for crt0

### ISSUE THREAD

**Issue by VladisM** [VladisM/m2tools#2]
With capabilities that linker script and its set eval is offering at this moment it is not possible to write fully functional crt0 routine as there is no way to get informations about how big BSS section is. There should be commands in eval environment that will return size of section or memory. Also start address of section or memory. 

Another missing feature of linker script is ability to put data into two memories. Because, data section have to be stored in memory where code is located, thus it will be distributed with binary, and have to be linker against RAM as data section is used for initialized variables and its content is often copied from read only memory into read write memory. 

**TODO list**
- [x] Add mem_size() and mem_begin()
- [x] Add section_size() and section_begin()
- [x] Add relevant information about functions above into doc
- [ ] Find and implement best way to deal with data in two memories problem

**Comment by VladisM** [comment]
Small improvement done in d18a5b7e3242634a718c10c695687f7cc953cad7. Now it is possible to use mem_begin() and mem_size() functions in linker script.

**Comment by VladisM** [comment]
Added section_size() and section_begin() in 0b26d0f20a5857aa214821b536ba5809f463dd24.

**Comment by VladisM** [comment]
Updated documentation in 1c404d9e19a4014ea55f6177668df8fa1771fee4.
